---
title: "Wine Modelling Analysis"
author: "Theodore Andrew, Alicia Lo, Sumit Patel"
date: "5/5/2018"
output: html_document
---


```{r include=FALSE}
# general
library(MASS)
library(caret)
library(tidyverse)
library(knitr)
library(kableExtra)
library(mlbench)

# specific
library(ISLR)
library(nnet)
library(ellipse)
library(randomForest)
library(gbm)
library(glmnet)
library(rpart)
library(rpart.plot)
library(ggplot2)
```


```{r}
wine = read.csv("wine.csv")
wine = wine[,-c(1, 2)]
wine$quality = as.factor(wine$quality)
```


```{r}
# Test-split the data
set.seed(42)
wine_idx = createDataPartition(wine$quality, p = 0.75, list = FALSE)
wine_trn = wine[wine_idx,]
wine_tst = wine[-wine_idx,]
```


Variable selection method


```{r}
y = as.numeric(wine$quality)
X = model.matrix(quality ~ ., wine)[, -12]

wine_lasso = cv.glmnet(X, y, alpha = 1)
plot(wine_lasso)
coef(wine_lasso, s = "lambda.1se")
```


Modelling Analysis

```{r}
calc_rmse = function(actual, predicted) {
  sqrt(mean((actual - predicted) ^ 2))
}
```

Multinomial Logistic Regression

```{r message=FALSE, warning=FALSE, include=FALSE}
wine_multi = train(quality ~ .,
                   data = wine_trn,
                   method = "multinom",
                   trControl = trainControl(method = "cv", number = 5)
                   )

multi_pred = predict(wine_multi, newdata = wine_tst)
rmse_multinom = calc_rmse(actual = as.numeric(wine_tst$quality), 
                          predicted = as.numeric(multi_pred))
```

KNN (without scaling)

```{r}
wine_knn_wo = train(quality ~ .,
                    data = wine_trn,
                    method = "knn",
                    trControl = trainControl(method = "cv", number = 5)
                    )

pred_knn_wo = predict(wine_knn_wo, newdata = wine_tst)
rmse_knn_wo = calc_rmse(actual = as.numeric(wine_tst$quality), 
                        predicted = as.numeric(pred_knn_wo))
```

KNN (with scaling)

```{r}
wine_knn_sc = train(quality ~ .,
                    data = wine_trn,
                    method = "knn",
                    trControl = trainControl(method = "cv", number = 5),
                    preProcess = c("center", "scale")
                    )

pred_knn_sc = predict(wine_knn_sc, newdata = wine_tst)
rmse_knn_sc = calc_rmse(actual = as.numeric(wine_tst$quality), 
                        predicted = as.numeric(pred_knn_sc))
```

LDA

```{r message=FALSE, warning=FALSE}
class_lda_mod = train(
  quality ~ .,
  data = wine_trn,
  trControl = trainControl(method = "cv", number = 10),
  method = "lda"
)

pred_lda_class = as.numeric(predict(class_lda_mod, wine_tst))
rmse_lda = calc_rmse(pred_lda_class, as.numeric(wine_tst$quality))
```

RDA

```{r message=FALSE, warning=FALSE}
class_rda_mod = train(
  quality ~ .,
  data = wine_trn,
  trControl = trainControl(method = "cv", number = 10),
  method = "rda"
)

pred_rda_class = as.numeric(predict(class_rda_mod, wine_tst))
rmse_rda = calc_rmse(pred_rda_class, as.numeric(wine_tst$quality))
```

NB

```{r message=FALSE, warning=FALSE}
wine_nb = train(quality ~ .,
                 data = wine_trn,
                 method = "nb",
                 trControl = trainControl(method = "cv", number = 5)
                 )

nb_pred = predict(wine_nb, newdata = wine_tst)
rmse_nb = calc_rmse(actual = as.numeric(wine_tst$quality), predicted = as.numeric(nb_pred))
```

Elastic Net

```{r message=FALSE, warning=FALSE}
wine_elnet = train(quality ~ .,
                   data = wine_trn,
                   method = "glmnet",
                   trControl = trainControl(method = "cv", number = 5)
                   )

pred_elnet = predict(wine_elnet, newdata = wine_tst)
rmse_elnet = calc_rmse(actual = as.numeric(wine_tst$quality),
                       predicted = as.numeric(pred_elnet))
```

Tree

```{r}
wine_tree = train(quality ~ .,
                   data = wine_trn,
                   method = "rpart",
                   trControl = trainControl(method = "cv", number = 5)
                   )

pred_tree = predict(wine_tree, newdata = wine_tst)
rmse_tree = calc_rmse(actual = as.numeric(wine_tst$quality),
                      predicted = as.numeric(pred_tree))
```

RF

```{r}
set.seed(9034)
wine_rf = train(quality ~ .,
                data = wine_trn,
                method = "rf",
                trControl = trainControl(method = "oob"),
                importance = T
                )

rf_pred = predict(wine_rf, newdata = wine_tst)
rmse_rf = calc_rmse(actual = as.numeric(wine_tst$quality), predicted = as.numeric(rf_pred))
```

GBM

```{r message=FALSE, warning=FALSE}
set.seed(9034)
wine_gbm = train(quality ~ .,
                 data = wine_trn,
                 method = "gbm",
                 trControl = trainControl(method = "cv", number = 5),
                 verbose = F
                 )

gbm_pred = predict(wine_gbm, newdata = wine_tst)
rmse_gbm = calc_rmse(actual = as.numeric(wine_tst$quality), predicted = as.numeric(gbm_pred))
```


```{r}
model_method = c("Multinomial Logistic Regression",
                 "KNN without scaling",
                 "KNN with scaling",
                 "LDA",
                 "RDA",
                 "Naive Bayes",
                 "Elastic Net",
                 "Tree",
                 "Random Forest",
                 "Gradient Boosted Model"
                 )

rmse_values = c(rmse_multinom, rmse_knn_wo, rmse_knn_sc, rmse_lda, rmse_rda, rmse_nb, 
                rmse_elnet, rmse_tree, rmse_rf, rmse_gbm)

class_summary = data.frame(model_method, rmse_values)
colnames(class_summary) = c("Model Method", "Testing RMSE")
```


```{r echo=FALSE}
kable_styling(kable(class_summary, format = "html", main = "Classification Testing RMSE", digits = 4), full_width = F)
```












